on:
  push:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true
      - name: build
        run: script/bootstrap
      - name: test
        run: script/cibuild --url-ignore "http://myfirstaws.com/,https://13.55.9.72/,https://ec2-13-55-9-72.ap-southeast-2.compute.amazonaws.com/"
